"""stage3 companies users orgs consultant_assignments

Revision ID: 87adfb05d90b
Revises: a45ba95ce770
Create Date: 2026-08-19 06:46:20.086050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '87adfb05d90b'
down_revision: Union[str, Sequence[str], None] = 'a45ba95ce770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('consultant_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('consultant_user_id', sa.Integer(), nullable=False),
    sa.Column('role_on_account', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['consultant_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'consultant_user_id', name='uq_company_consultant')
    )
    op.create_index('ix_consultant_assignment_company', 'consultant_assignments', ['company_id'], unique=False)
    op.create_index('ix_consultant_assignment_user', 'consultant_assignments', ['consultant_user_id'], unique=False)
    op.add_column('company', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('company', sa.Column('registration_date', sa.Date(), nullable=True))
    op.add_column('company', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('company', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_company_deleted_at'), 'company', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_company_organization_id'), 'company', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'company', 'organizations', ['organization_id'], ['id'])
    op.add_column('user', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_deleted_at'), 'user', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'user', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_deleted_at'), table_name='user')
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'organization_id')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_index(op.f('ix_company_organization_id'), table_name='company')
    op.drop_index(op.f('ix_company_deleted_at'), table_name='company')
    op.drop_column('company', 'deleted_at')
    op.drop_column('company', 'updated_at')
    op.drop_column('company', 'registration_date')
    op.drop_column('company', 'organization_id')
    op.drop_index('ix_consultant_assignment_user', table_name='consultant_assignments')
    op.drop_index('ix_consultant_assignment_company', table_name='consultant_assignments')
    op.drop_table('consultant_assignments')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
