"""stage4 data foundation

Master data, upload types, datasets, files, jobs, audit, integrations.

Hand-written (not autogenerated) because:
  1) Autogenerate ordered tables alphabetically, breaking FK dependencies.
  2) datasets <-> dataset_versions has a circular FK (datasets.current_version_id
     points at dataset_versions.id, dataset_versions.dataset_id points back).
     We resolve it by creating the FK AFTER both tables exist.

Revision ID: c4a1e2b3d5f7
Revises: 87adfb05d90b
Create Date: 2026-08-29
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'c4a1e2b3d5f7'
down_revision: Union[str, Sequence[str], None] = '87adfb05d90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- 1. Add segregation-of-duties flag to companies ---
    op.add_column('company', sa.Column(
        'enforce_upload_approval_segregation', sa.Boolean(),
        nullable=False, server_default=sa.true(),
    ))

    # --- 2. Master data (no cross-deps beyond company) ---
    op.create_table(
        'sites',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('company_id', sa.Integer(), sa.ForeignKey('company.id'), nullable=False),
        sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('site_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.UniqueConstraint('company_id', 'code', name='uq_site_company_code'),
    )
    op.create_index('ix_sites_public_id', 'sites', ['public_id'], unique=True)
    op.create_index('ix_sites_company_id', 'sites', ['company_id'])
    op.create_index('ix_sites_deleted_at', 'sites', ['deleted_at'])
    op.create_index('ix_site_company_active', 'sites', ['company_id', 'is_active'])

    op.create_table(
        'business_units',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('company_id', sa.Integer(), sa.ForeignKey('company.id'), nullable=False),
        sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('parent_id', sa.Integer(), sa.ForeignKey('business_units.id'), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.UniqueConstraint('company_id', 'code', name='uq_bu_company_code'),
    )
    op.create_index('ix_business_units_public_id', 'business_units', ['public_id'], unique=True)
    op.create_index('ix_business_units_company_id', 'business_units', ['company_id'])
    op.create_index('ix_business_units_deleted_at', 'business_units', ['deleted_at'])
    op.create_index('ix_bu_company_parent', 'business_units', ['company_id', 'parent_id'])

    op.create_table(
        'departments',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('company_id', sa.Integer(), sa.ForeignKey('company.id'), nullable=False),
        sa.Column('business_unit_id', sa.Integer(), sa.ForeignKey('business_units.id'), nullable=True),
        sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.UniqueConstraint('company_id', 'code', name='uq_dept_company_code'),
    )
    op.create_index('ix_departments_public_id', 'departments', ['public_id'], unique=True)
    op.create_index('ix_departments_company_id', 'departments', ['company_id'])
    op.create_index('ix_departments_deleted_at', 'departments', ['deleted_at'])
    op.create_index('ix_dept_company_bu', 'departments', ['company_id', 'business_unit_id'])

    # --- 3. Upload types (referenced by datasets) ---
    op.create_table(
        'upload_types',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('allowed_mime_types', sa.JSON(), nullable=True),
        sa.Column('max_file_size_bytes', sa.Integer(), nullable=False, server_default='26214400'),
        sa.Column('template_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('validation_policy_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('processing_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='async'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
    )
    op.create_index('ix_upload_types_code', 'upload_types', ['code'], unique=True)

    # --- 4. Datasets — created WITHOUT the current_version_id FK; added later ---
    op.create_table(
        'datasets',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('company_id', sa.Integer(), sa.ForeignKey('company.id'), nullable=False),
        sa.Column('site_id', sa.Integer(), sa.ForeignKey('sites.id'), nullable=True),
        sa.Column('business_unit_id', sa.Integer(), sa.ForeignKey('business_units.id'), nullable=True),
        sa.Column('department_id', sa.Integer(), sa.ForeignKey('departments.id'), nullable=True),
        sa.Column('upload_type_id', sa.Integer(), sa.ForeignKey('upload_types.id'), nullable=False),
        sa.Column('reporting_period_start', sa.Date(), nullable=False),
        sa.Column('reporting_period_end', sa.Date(), nullable=False),
        sa.Column('reporting_frequency', sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False, server_default='quarterly'),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False, server_default='draft'),
        sa.Column('current_version_id', sa.Integer(), nullable=True),  # FK added later
        sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_by', sa.Integer(), sa.ForeignKey('user.id'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
    )
    op.create_index('ix_datasets_public_id', 'datasets', ['public_id'], unique=True)
    op.create_index('ix_datasets_company_id', 'datasets', ['company_id'])
    op.create_index('ix_datasets_upload_type_id', 'datasets', ['upload_type_id'])
    op.create_index('ix_datasets_status', 'datasets', ['status'])
    op.create_index('ix_datasets_deleted_at', 'datasets', ['deleted_at'])
    op.create_index('ix_dataset_company_status', 'datasets', ['company_id', 'status'])
    op.create_index('ix_dataset_company_period', 'datasets', ['company_id', 'reporting_period_start'])

    # --- 5. Dataset versions (depends on datasets) ---
    op.create_table(
        'dataset_versions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('dataset_id', sa.Integer(), sa.ForeignKey('datasets.id'), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False, server_default='draft'),
        sa.Column('uploaded_by', sa.Integer(), sa.ForeignKey('user.id'), nullable=False),
        sa.Column('submitted_at', sa.DateTime(), nullable=True),
        sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.UniqueConstraint('dataset_id', 'version_number', name='uq_dsv_dataset_versionno'),
    )
    op.create_index('ix_dataset_versions_public_id', 'dataset_versions', ['public_id'], unique=True)
    op.create_index('ix_dataset_versions_dataset_id', 'dataset_versions', ['dataset_id'])
    op.create_index('ix_dsv_dataset_status', 'dataset_versions', ['dataset_id', 'status'])

    # --- 6. NOW resolve the circular FK: datasets.current_version_id -> dataset_versions.id ---
    op.create_foreign_key(
        'fk_datasets_current_version',
        'datasets', 'dataset_versions',
        ['current_version_id'], ['id'],
    )

    # --- 7. Dataset files ---
    op.create_table(
        'dataset_files',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('dataset_version_id', sa.Integer(), sa.ForeignKey('dataset_versions.id'), nullable=False),
        sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('size_bytes', sa.Integer(), nullable=False),
        sa.Column('sha256_checksum', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('uploaded_by', sa.Integer(), sa.ForeignKey('user.id'), nullable=False),
        sa.Column('uploaded_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
    )
    op.create_index('ix_dataset_files_public_id', 'dataset_files', ['public_id'], unique=True)
    op.create_index('ix_dataset_files_dataset_version_id', 'dataset_files', ['dataset_version_id'])
    op.create_index('ix_dataset_files_sha256_checksum', 'dataset_files', ['sha256_checksum'])
    op.create_index('ix_df_version_role', 'dataset_files', ['dataset_version_id', 'role'])

    # --- 8. Processing jobs (independent) ---
    op.create_table(
        'processing_jobs',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('job_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('subject_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('subject_id', sa.Integer(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False, server_default='pending'),
        sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('max_attempts', sa.Integer(), nullable=False, server_default='3'),
        sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('payload', sa.JSON(), nullable=True),
        sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('scheduled_at', sa.DateTime(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
    )
    op.create_index('ix_processing_jobs_status', 'processing_jobs', ['status'])
    op.create_index('ix_processing_jobs_idempotency_key', 'processing_jobs',
                    ['idempotency_key'], unique=True)
    op.create_index('ix_pj_status_scheduled', 'processing_jobs', ['status', 'scheduled_at'])
    op.create_index('ix_pj_subject', 'processing_jobs', ['subject_type', 'subject_id'])

    # --- 9. Audit logs (append-only) ---
    op.create_table(
        'audit_logs',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('organization_id', sa.Integer(), sa.ForeignKey('organizations.id'), nullable=True),
        sa.Column('company_id', sa.Integer(), sa.ForeignKey('company.id'), nullable=True),
        sa.Column('actor_user_id', sa.Integer(), sa.ForeignKey('user.id'), nullable=True),
        sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('entity_id', sa.Integer(), nullable=False),
        sa.Column('entity_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('changes', sa.JSON(), nullable=True),
        sa.Column('occurred_at', sa.DateTime(), nullable=False),
    )
    op.create_index('ix_audit_logs_organization_id', 'audit_logs', ['organization_id'])
    op.create_index('ix_audit_logs_company_id', 'audit_logs', ['company_id'])
    op.create_index('ix_audit_logs_occurred_at', 'audit_logs', ['occurred_at'])
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'])
    op.create_index('ix_audit_company_time', 'audit_logs', ['company_id', 'occurred_at'])
    op.create_index('ix_audit_actor', 'audit_logs', ['actor_user_id'])

    # --- 10. Integrations (stub only) ---
    op.create_table(
        'integrations',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('company_id', sa.Integer(), sa.ForeignKey('company.id'), nullable=False),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False, server_default='configured'),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.Column('last_sync_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
    )
    op.create_index('ix_integrations_company_id', 'integrations', ['company_id'])
    op.create_index('ix_integration_company_type', 'integrations', ['company_id', 'type'])


def downgrade() -> None:
    # Reverse order; break circular FK first.
    op.drop_table('integrations')
    op.drop_table('audit_logs')
    op.drop_table('processing_jobs')
    op.drop_table('dataset_files')
    op.drop_constraint('fk_datasets_current_version', 'datasets', type_='foreignkey')
    op.drop_table('dataset_versions')
    op.drop_table('datasets')
    op.drop_table('upload_types')
    op.drop_table('departments')
    op.drop_table('business_units')
    op.drop_table('sites')
    op.drop_column('company', 'enforce_upload_approval_segregation')
