"""stage5 review workflow

Adds:
- reviews: per-assignment review record (push mode; supports pull via nullable reviewer_user_id)
- review_comments: threaded via nullable parent_comment_id (self-FK)
- notifications: user-facing feed
- notification_outbox: transactional outbox pattern for reliable delivery
- dataset_versions.review_decision_summary: JSONB cache for listing performance

Hand-written (not autogenerated) because our Stage 4 experience showed
autogenerate mis-orders tables with self-referential FKs. This migration
creates review_comments WITHOUT the parent_comment_id FK, then adds it
separately — same pattern as Stage 4's datasets<->dataset_versions.

Revision ID: d8c2f7a3b1e4
Revises: c4a1e2b3d5f7
Create Date: 2026-08-30
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'd8c2f7a3b1e4'
down_revision: Union[str, Sequence[str], None] = 'c4a1e2b3d5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add cache column to dataset_versions
    op.add_column('dataset_versions', sa.Column(
        'review_decision_summary', sa.JSON(), nullable=True
    ))

    # 2. Reviews table
    op.create_table(
        'reviews',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('dataset_version_id', sa.Integer(),
                  sa.ForeignKey('dataset_versions.id'), nullable=False),
        # Nullable: null == unclaimed queue entry (pull mode, future).
        # Stage 5 push mode always sets it, but the column stays nullable
        # to avoid a future migration.
        sa.Column('reviewer_user_id', sa.Integer(),
                  sa.ForeignKey('user.id'), nullable=True),
        sa.Column('tier', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False, server_default='pending'),
        sa.Column('assigned_by', sa.Integer(),
                  sa.ForeignKey('user.id'), nullable=False),
        sa.Column('assigned_at', sa.DateTime(), nullable=False),
        sa.Column('decided_at', sa.DateTime(), nullable=True),
        sa.Column('decision_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
    )
    op.create_index('ix_reviews_public_id', 'reviews', ['public_id'], unique=True)
    op.create_index('ix_reviews_dataset_version_id', 'reviews', ['dataset_version_id'])
    op.create_index('ix_review_version_status', 'reviews',
                    ['dataset_version_id', 'status'])
    op.create_index('ix_review_reviewer', 'reviews', ['reviewer_user_id'])

    # 3. Review comments — created WITHOUT the parent self-FK first
    op.create_table(
        'review_comments',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('dataset_version_id', sa.Integer(),
                  sa.ForeignKey('dataset_versions.id'), nullable=False),
        # parent_comment_id: nullable (root comment) or points at another
        # review_comments row (reply). Self-FK added AFTER table exists.
        sa.Column('parent_comment_id', sa.Integer(), nullable=True),
        sa.Column('author_user_id', sa.Integer(),
                  sa.ForeignKey('user.id'), nullable=False),
        sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False, server_default='general'),
        sa.Column('field_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
    )
    op.create_index('ix_review_comments_public_id', 'review_comments',
                    ['public_id'], unique=True)
    op.create_index('ix_rc_version', 'review_comments', ['dataset_version_id'])
    op.create_index('ix_rc_parent', 'review_comments', ['parent_comment_id'])
    # NOW add the self-FK
    op.create_foreign_key(
        'fk_review_comments_parent',
        'review_comments', 'review_comments',
        ['parent_comment_id'], ['id'],
    )

    # 4. Notifications
    op.create_table(
        'notifications',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('recipient_user_id', sa.Integer(),
                  sa.ForeignKey('user.id'), nullable=False),
        sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('entity_id', sa.Integer(), nullable=True),
        sa.Column('entity_public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('read_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
    )
    op.create_index('ix_notifications_recipient_user_id', 'notifications',
                    ['recipient_user_id'])
    op.create_index('ix_notif_recipient_unread', 'notifications',
                    ['recipient_user_id', 'is_read'])
    op.create_index('ix_notif_recipient_created', 'notifications',
                    ['recipient_user_id', 'created_at'])

    # 5. Notification outbox
    op.create_table(
        'notification_outbox',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('payload', sa.JSON(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False, server_default='pending'),
        sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('dispatched_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
    )
    op.create_index('ix_outbox_status_created', 'notification_outbox',
                    ['status', 'created_at'])


def downgrade() -> None:
    op.drop_table('notification_outbox')
    op.drop_table('notifications')
    op.drop_constraint('fk_review_comments_parent', 'review_comments', type_='foreignkey')
    op.drop_table('review_comments')
    op.drop_table('reviews')
    op.drop_column('dataset_versions', 'review_decision_summary')
