"""layer1 structured kpi data foundation

Adds:
- kpi_definitions: pure structural catalog (code, display name, unit hint,
  which upload_type it belongs to). Contains NO formula, weight, or
  emission-factor content — see app/models/kpi.py's module docstring for
  the full design rationale and explicit boundary.
- kpi_values: extracted, provenance-rich, raw-as-reported measurements.
  Traces back to exact dataset/version/file/row. Company-scoped
  denormalized for direct tenant filtering, matching the pattern already
  used by every other tenant-scoped table in this backend.

Hand-written (not autogenerated), following the same convention as Stage 4
and Stage 5's migrations.

Revision ID: e1f4a8c9d2b6
Revises: d8c2f7a3b1e4
Create Date: 2026-09-02
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'e1f4a8c9d2b6'
down_revision: Union[str, Sequence[str], None] = 'd8c2f7a3b1e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. KPI definitions — pure structural catalog, no formulas/weights/factors.
    op.create_table(
        'kpi_definitions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('unit_hint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('upload_type_id', sa.Integer(),
                  sa.ForeignKey('upload_types.id'), nullable=False),
        sa.Column('data_type', sqlmodel.sql.sqltypes.AutoString(),
                  nullable=False, server_default='numeric'),
        sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('created_at', sa.DateTime(), nullable=False),
    )
    op.create_unique_constraint(
        'uq_kpi_definition_code_version', 'kpi_definitions', ['code', 'version']
    )
    op.create_index('ix_kpi_definition_upload_type', 'kpi_definitions', ['upload_type_id'])

    # 2. KPI values — extracted, raw, provenance-rich measurements.
    op.create_table(
        'kpi_values',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('public_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),

        sa.Column('dataset_id', sa.Integer(), sa.ForeignKey('datasets.id'), nullable=False),
        sa.Column('dataset_version_id', sa.Integer(),
                  sa.ForeignKey('dataset_versions.id'), nullable=False),
        sa.Column('source_file_id', sa.Integer(),
                  sa.ForeignKey('dataset_files.id'), nullable=False),
        sa.Column('source_row_number', sa.Integer(), nullable=False),
        sa.Column('extraction_job_id', sa.Integer(),
                  sa.ForeignKey('processing_jobs.id'), nullable=True),

        sa.Column('company_id', sa.Integer(), sa.ForeignKey('company.id'), nullable=False),
        sa.Column('site_id', sa.Integer(), sa.ForeignKey('sites.id'), nullable=True),

        sa.Column('kpi_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('value', sa.Float(), nullable=False),
        sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('attributes', sa.JSON(), nullable=False, server_default='{}'),

        sa.Column('reporting_period_start', sa.Date(), nullable=False),
        sa.Column('reporting_period_end', sa.Date(), nullable=False),

        sa.Column('created_at', sa.DateTime(), nullable=False),
    )
    op.create_index('ix_kpi_values_public_id', 'kpi_values', ['public_id'], unique=True)
    op.create_unique_constraint(
        'uq_kpi_value_source_row_metric', 'kpi_values',
        ['dataset_version_id', 'source_file_id', 'source_row_number', 'kpi_code'],
    )
    op.create_index('ix_kpi_value_company_period', 'kpi_values',
                    ['company_id', 'reporting_period_start', 'reporting_period_end'])
    op.create_index('ix_kpi_value_dataset_version', 'kpi_values', ['dataset_version_id'])
    op.create_index('ix_kpi_value_site', 'kpi_values', ['site_id'])
    op.create_index('ix_kpi_value_kpi_code', 'kpi_values', ['kpi_code'])


def downgrade() -> None:
    op.drop_table('kpi_values')
    op.drop_table('kpi_definitions')
